config/routes.rb
Rails.application.routes.draw do
  resources :ownerships
  resources :itineraries
  resources :events
  get 'home/index'

  # devise_for :users
  use_doorkeeper

  devise_for :users,
    path: 'user',
    path_names: { sign_in: 'login', sign_out: 'logout' },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations'
      # unlocks: 'users/unlocks',
      # omniauth_callbacks: 'users/omniauth_callbacks'
    }
  devise_scope :user do
    get 'users/oauth_redirect', to: 'users/sessions#oauth'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :itinerary
	validates :itinerary, presence: true

	has_attached_file :thumbnail,
                  styles: { thumb: ["400x200#", :jpg],
                  					original: ['1024x768>', :jpg]  },
                  # convert_options: { thumb: "-quality 100 -strip",
                  #                    original: "-quality 100 -strip" },
                  url: "/event_images/:hash.:extension",
                  hash_secret: Rails.application.secrets.paperclip_image_hash_secret

	validates_attachment :thumbnail,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
                     size: { in: 0..5000.kilobytes }

	after_create :append_event_to_itinerary
	after_destroy :remove_event_from_itinerary

	private

	def append_event_to_itinerary
		self.itinerary.events_id.push(self.id)
		self.itinerary.save
	end

	def remove_event_from_itinerary
		self.itinerary.events_id.delete(self.id)
		self.itinerary.save
	end
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
	has_many :events, dependent: :nullify


	def initialize(*args, &block)
	  super 
	  if self.events_id == nil
	  	self.events_id = []
	  end
	end
end

app/models/ownership.rb
class Ownership < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

  before_action :authenticate_user!

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new(CONFIG[:default_event_coordinates])
    @itinerary = Itinerary.find(params[:itinerary_id])
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @itinerary = Itinerary.find(event_params[:itinerary_id])
    if @event.save
      redirect_to @itinerary, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      @itinerary = Itinerary.find(@event.itinerary_id)
      redirect_to @itinerary, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @itinerary = Itinerary.find(@event.itinerary_id)
    @event.destroy
    redirect_to @itinerary, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:title, :content, :thumbnail_url, :entity, :schedule, :lat, :lng, :itinerary_id, :thumbnail)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to itineraries_path
  	else 
  		render
  	end
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: [:show, :edit, :update, :destroy]

  # GET /itineraries
  def index
    @itineraries = Itinerary.all
  end

  # GET /itineraries/1
  def show
    @events = Event.find(@itinerary.events_id)
  end

  # GET /itineraries/new
  def new
    @itinerary = Itinerary.new
  end

  # GET /itineraries/1/edit
  def edit
  end

  # POST /itineraries
  def create
    @itinerary = Itinerary.new(itinerary_params)

    if @itinerary.save
      redirect_to @itinerary, notice: 'Itinerary was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /itineraries/1
  def update
    if @itinerary.update(itinerary_params)
      redirect_to @itinerary, notice: 'Itinerary was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /itineraries/1
  def destroy
    @itinerary.destroy
    redirect_to itineraries_url, notice: 'Itinerary was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerary
      @itinerary = Itinerary.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def itinerary_params
      params.require(:itinerary).permit(:title, :content)
    end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  before_action :set_ownership, only: [:show, :edit, :update, :destroy]

  # GET /ownerships
  def index
    @ownerships = Ownership.all
  end

  # GET /ownerships/1
  def show
  end

  # GET /ownerships/new
  def new
    @ownership = Ownership.new
  end

  # GET /ownerships/1/edit
  def edit
  end

  # POST /ownerships
  def create
    @ownership = Ownership.new(ownership_params)

    if @ownership.save
      redirect_to @ownership, notice: 'Ownership was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ownerships/1
  def update
    if @ownership.update(ownership_params)
      redirect_to @ownership, notice: 'Ownership was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ownerships/1
  def destroy
    @ownership.destroy
    redirect_to ownerships_url, notice: 'Ownership was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ownership
      @ownership = Ownership.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def ownership_params
      params.require(:ownership).permit(:role)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :doorkeeper_authorize!, only: [:oauth]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # GET /resource/oauth_sign_in
  def oauth
    resource = doorkeeper_token.resource_owner_id &&
      User.find_by(id: doorkeeper_token.resource_owner_id)
    if resource
      sign_in(resource)
      redirect_to params[:return_to] || after_sign_in_path_for(resource)
    else
      redirect_to params[:return_to] || root_url
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/ownerships_helper.rb
module OwnershipsHelper
end

app/views/events/_event.html.erb
<%= render 'form', event: @event %>

app/views/events/_event_list_item.html.erb
<%= link_to(edit_event_path(event)) do %>
	<div class="event-list-item">
		<% if event.thumbnail != nil %>
			<%= image_tag(event.thumbnail.url(:thumb), :class => "thumbnail-image-size", :alt => "thumbnail") %>
		<% end %>
		<div>
			<strong><%= event.title %></strong>
		</div>
		<div>
			<p><%= event.content %></p>
		</div>
		<br>
	</div>
<% end %>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="field">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="col-md-8">
      <div class="field">
        <%= f.datetime_select :schedule %>
        <span>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">
      <% if @event.thumbnail != nil %>
        <%= image_tag(@event.thumbnail.url(:thumb), :class => "form-thumbnail-image-size", :alt => "thumbnail") %>
      <% end %>
      <%= f.file_field :thumbnail %>
    </div>
    <div class="col-md-8">
      <%= content_tag :div, "",
        id: "google-map-container",
        class: "text-xs-center",
        data: { lat: @event.lat, lng: @event.lng, marker_title: @event.title, api_key: Rails.application.secrets.google_browser_key } %>
      <div class="field" hidden>
        <%= f.label :lat %>
        <%= f.text_field :lat %>
        <%= f.label :lng %>
        <%= f.text_field :lng %>
      </div>

      <div>
        <%= text_field_tag(:address) %>
        <!-- <input id="reverse_geocode" type="button" value="Geocode"> -->
      </div>
    </div>
  </div>

  <br>
  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <%= f.text_area :content %>
      </div>
    </div>
  </div>

  <% if @itinerary != nil %>
    <%= f.hidden_field :itinerary_id, :value => @itinerary.id %>
  <% end %>

  <div class="actions submit_button">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<br>
<%= render 'form', event: @event %>
<br>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Entity</th>
      <th>Schedule</th>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.content %></td>
        <td><%= event.entity %></td>
        <td><%= event.schedule %></td>
        <td><%= event.lat %></td>
        <td><%= event.lng %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @event.entity %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @event.schedule %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @event.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @event.lng %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/itineraries/_form.html.erb
<%= form_for(itinerary) do |f| %>
  <% if itinerary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(itinerary.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

      <ul>
      <% itinerary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itineraries/edit.html.erb
<h1>Editing Itinerary</h1>

<%= render 'form', itinerary: @itinerary %>

app/views/itineraries/index.html.erb
<h1>Itineraries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itineraries.each do |itinerary| %>
      <tr>
        <td><%= itinerary.title %></td>
        <td><%= itinerary.content %></td>
        <td><%= link_to 'Show', itinerary %></td>
        <td><%= link_to 'Destroy', itinerary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itinerary', new_itinerary_path %>

app/views/itineraries/new.html.erb
<h1>New Itinerary</h1>

<%= render 'form', itinerary: @itinerary %>

<%= link_to 'Back', itineraries_path %>

app/views/itineraries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
	<p>
	  <strong>Title:</strong>
	  <%= @itinerary.title %>
	</p>
	<p>
	  <strong>Description:</strong>
	  <%= @itinerary.content %> | <%= link_to 'Edit', edit_itinerary_path(@itinerary) %>
	</p>
</div>

<div class="col-md-12">
  <%= content_tag :div, "",
    id: "itinerary-roadmap-container",
    class: "text-xs-center itinerary-roadmap",
    data: { events: @events, api_key: Rails.application.secrets.google_browser_key } %>
</div>

<div>
	<% if @events != nil %>
		<% @events.each do |event| %>
			<div class='col-md-4'>
				<%= render partial: 'events/event_list_item', object: event, as: 'event'%>
			</div>
		<% end %>
	<% end %>
	<div class='col-md-4 event-list-item', id='add-event-list-item'>
		<%= link_to 'New Event', new_event_path(itinerary_id: @itinerary.id) %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%# The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags %>
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stepnote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_browser_key}&libraries=visualization"></script>
  </head>

  <%= content_tag :body,
    class: "#{params[:controller].parameterize} #{params[:action].parameterize}",
    data: @_body_data do  %>

    <div class="masthead container-fluid custom-container">
      <nav class="navbar navbar-light navbar-fixed-top" data-scroll-background-color="black">
        <div class="container-fluid custom-container">
        <%= link_to image_tag("boar_logo.png"), root_path, class: "navbar-brand" %>
          <ul class="nav navbar-nav float-xs-right">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to '#', class: "nav-link dropdown-toggle", data: { toggle: "dropdown"} do %>
                  <i class="fa fa-user"></i>
                  <%= current_user.email %>
                <% end %>
                <div class="dropdown-menu dropdown-menu-right">
                  <%= link_to destroy_user_session_path, class: "dropdown-item" do %>
                    <i class="fa fa-sign-out"></i>
                    <%= t(".logout") %>
                  <% end %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link" do %>
                  <i class="fa fa-sign-in"></i>
                  <%= t(".login") %>
               <% end %>
            <% end %>
          </ul>
        </div>

      </nav>
    </div>




 		<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
  <!-- </body> -->
  <% end %>
</html>

app/views/ownerships/_form.html.erb
<%= form_for(ownership) do |f| %>
  <% if ownership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ownership.errors.count, "error") %> prohibited this ownership from being saved:</h2>

      <ul>
      <% ownership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ownerships/edit.html.erb
<h1>Editing Ownership</h1>

<%= render 'form', ownership: @ownership %>

<%= link_to 'Show', @ownership %> |
<%= link_to 'Back', ownerships_path %>

app/views/ownerships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ownerships</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ownerships.each do |ownership| %>
      <tr>
        <td><%= ownership.role %></td>
        <td><%= link_to 'Show', ownership %></td>
        <td><%= link_to 'Edit', edit_ownership_path(ownership) %></td>
        <td><%= link_to 'Destroy', ownership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ownership', new_ownership_path %>

app/views/ownerships/new.html.erb
<h1>New Ownership</h1>

<%= render 'form', ownership: @ownership %>

<%= link_to 'Back', ownerships_path %>

app/views/ownerships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @ownership.role %>
</p>

<%= link_to 'Edit', edit_ownership_path(@ownership) %> |
<%= link_to 'Back', ownerships_path %>